### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by dariusk** [v21/tracery#5]
Can you update the npm package for this library? I was going by the readme on the published package and was confused as to why modifiers weren't working until I came here and saw the updated readme. Thanks!

**Comment by MichaelPaulukonis** [comment]
Adding the github repo (to `package.json`) so it points here could be helpful, to avoid situations like [this](https://github.com/galaxykate/tracery/issues/30), where people only found the main Tracery repo.

**Comment by v21** [comment]
Done! (this took a lot longer than it should, sorry)
