### ISSUE TITLE
Support for other language modifiers

### ISSUE THREAD

**Issue by mycaule** [v21/tracery#8]
Hello, I would like to add support for French in the modifiers.
Can I make a pull request to extract the code related to modifiers and add a `baseFrModifiers` ?

Or do you think I should make that PR in the main repo of galaxykate ?

Thank you for having built this node.js package by the way.

It looks like there is no modification since one year, but I think there might be interesting stuff to do with this package and the Google Home as mentionned in this [Google Labs blog post](https://medium.com/@nicolehe/voice-technology-is-an-opportunity-to-make-weird-stuff-d4296ce7448a).

**Comment by mycaule** [comment]
See the ES6 refactorisation here https://github.com/mycaule/epures

**Comment by v21** [comment]
Oh, this is lovely. Yes, please do send through a PR.

I'm unsure how Kate wants to handle stuff - originally the modifiers were built in, but for this version I have pulled them out into ones selectable by language, so I'm unsure if they make sense to add to the upstream repo. 

And from a quick glimpse of the ES6 repo, that looks great! I'd love a more maintainable version of tracery.
